table 'Pupil Info'
	lineageTag: 537b9c87-def3-439e-a205-424e9b833069

	column 'School Name'
		dataType: string
		lineageTag: 518c92e5-89cb-433c-8630-fdeed3b734cd
		summarizeBy: none
		sourceColumn: School Name

		annotation SummarizationSetBy = Automatic

	column URN
		dataType: int64
		formatString: 0
		lineageTag: eb03cd94-697c-4d34-b72e-85e5c724e9ac
		summarizeBy: none
		sourceColumn: URN

		annotation SummarizationSetBy = Automatic

	column Attribute
		dataType: string
		lineageTag: 177d2e75-e9b8-4247-a67a-de997d775548
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column 'Number of Pupils'
		dataType: int64
		formatString: 0
		lineageTag: 56e29e3c-4045-4a5e-959b-bdd9d831c585
		summarizeBy: sum
		sourceColumn: Number of Pupils

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: ebbceebc-c5ee-42fe-9e09-4c573c2abf74
		summarizeBy: none
		sourceColumn: Type
		sortByColumn: Custom

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Year Group'
		dataType: string
		lineageTag: a85081a2-5170-4484-8816-dfdb74d4328c
		summarizeBy: none
		sourceColumn: Year Group
		sortByColumn: 'Year group Sort Order'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Year group Sort Order'
		dataType: double
		lineageTag: c6605570-83dd-4adf-8fc6-8319ba6453b9
		summarizeBy: sum
		sourceColumn: Year group Sort Order

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Custom
		dataType: double
		lineageTag: 8cb00fa4-66f9-4c3e-b14c-188409e93c02
		summarizeBy: sum
		sourceColumn: Custom

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total NOR'
		dataType: int64
		formatString: 0
		lineageTag: 6905ad52-257d-468f-a48e-7ff27bcb9b6a
		summarizeBy: sum
		sourceColumn: Total NOR

		annotation SummarizationSetBy = Automatic

	column 'Total PAN'
		dataType: int64
		formatString: 0
		lineageTag: 6b436149-8262-40df-8ac5-a9e05db2c575
		summarizeBy: sum
		sourceColumn: Total PAN

		annotation SummarizationSetBy = Automatic

	column 'Total FPAN'
		dataType: int64
		formatString: 0
		lineageTag: 1936419a-af62-4c9d-8d5b-fa516cc4c7f6
		summarizeBy: sum
		sourceColumn: Total FPAN

		annotation SummarizationSetBy = Automatic

	column 'Source.Name'
		dataType: string
		lineageTag: 089c3fba-029f-4b7d-8aa5-449274c3fefb
		summarizeBy: none
		sourceColumn: Source.Name

		annotation SummarizationSetBy = Automatic

	partition 'Pupil Info' = m
		mode: import
		source =
				let
				    Source = SharePoint.Files("https://1stplanner1.sharepoint.com/sites/1stPlannerInsites/", [ApiVersion = 15]),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Name] = "Master Sufficiency Data.xlsx")),
				    #"Filtered Hidden Files1" = Table.SelectRows(#"Filtered Rows", each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (2)", each #"Transform File (2)"([Content])),
				    #"Renamed Columns4" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns4", {"Source.Name", "Transform File (2)"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (2)", Table.ColumnNames(#"Transform File (2)"(#"Sample File (2)"))),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"School Name", type text}, {"URN", Int64.Type}, {"NOR - E1", Int64.Type}, {"NOR - E2", Int64.Type}, {"NOR - N1", Int64.Type}, {"NOR - N2", Int64.Type}, {"NOR - R", Int64.Type}, {"NOR - 1", Int64.Type}, {"NOR - 2", Int64.Type}, {"NOR - 3", Int64.Type}, {"NOR - 4", Int64.Type}, {"NOR - 5", Int64.Type}, {"NOR - 6", Int64.Type}, {"NOR - 7", Int64.Type}, {"NOR - 8", Int64.Type}, {"NOR - 9", Int64.Type}, {"NOR - 10", Int64.Type}, {"NOR - 11", Int64.Type}, {"NOR - 12", type any}, {"NOR - 13", type any}, {"NOR - 14", type any}, {"PAN - E1", type any}, {"PAN - E2", type any}, {"PAN - N1", Int64.Type}, {"PAN - N2", Int64.Type}, {"PAN - R", Int64.Type}, {"PAN - 1", Int64.Type}, {"PAN - 2", Int64.Type}, {"PAN - 3", Int64.Type}, {"PAN - 4", Int64.Type}, {"PAN - 5", Int64.Type}, {"PAN - 6", Int64.Type}, {"PAN - 7", Int64.Type}, {"PAN - 8", Int64.Type}, {"PAN - 9", Int64.Type}, {"PAN - 10", Int64.Type}, {"PAN - 11", Int64.Type}, {"PAN - 12", type any}, {"PAN - 13", type any}, {"PAN - 14", type any}, {"FPAN - E1", Int64.Type}, {"FPAN - E2", Int64.Type}, {"FPAN - N1", Int64.Type}, {"FPAN - N2", Int64.Type}, {"FPAN - R", Int64.Type}, {"FPAN - 1", Int64.Type}, {"FPAN - 2", Int64.Type}, {"FPAN - 3", Int64.Type}, {"FPAN - 4", Int64.Type}, {"FPAN - 5", Int64.Type}, {"FPAN - 6", Int64.Type}, {"FPAN - 7", Int64.Type}, {"FPAN - 8", Int64.Type}, {"FPAN - 9", Int64.Type}, {"FPAN - 10", Int64.Type}, {"FPAN - 11", Int64.Type}, {"FPAN - 12", type any}, {"FPAN - 13", type any}, {"FPAN - 14", type any}, {"EHCP NOR - E1", type any}, {"EHCP NOR - E2", type any}, {"EHCP NOR - N1", type any}, {"EHCP NOR - N2", type any}, {"EHCP NOR - R", Int64.Type}, {"EHCP NOR - 1", Int64.Type}, {"EHCP NOR - 2", Int64.Type}, {"EHCP NOR - 3", Int64.Type}, {"EHCP NOR - 4", Int64.Type}, {"EHCP NOR - 5", Int64.Type}, {"EHCP NOR - 6", Int64.Type}, {"EHCP NOR - 7", Int64.Type}, {"EHCP NOR - 8", Int64.Type}, {"EHCP NOR - 9", Int64.Type}, {"EHCP NOR - 10", Int64.Type}, {"EHCP NOR - 11", Int64.Type}, {"EHCP NOR - 12", type any}, {"EHCP NOR - 13", type any}, {"EHCP NOR - 14", type any}, {"EHCP PAN - E1", type any}, {"EHCP PAN - E2", type any}, {"EHCP PAN - N1", type any}, {"EHCP PAN - N2", type any}, {"EHCP PAN - R", Int64.Type}, {"EHCP PAN - 1", Int64.Type}, {"EHCP PAN - 2", Int64.Type}, {"EHCP PAN - 3", Int64.Type}, {"EHCP PAN - 4", Int64.Type}, {"EHCP PAN - 5", Int64.Type}, {"EHCP PAN - 6", Int64.Type}, {"EHCP PAN - 7", Int64.Type}, {"EHCP PAN - 8", Int64.Type}, {"EHCP PAN - 9", Int64.Type}, {"EHCP PAN - 10", Int64.Type}, {"EHCP PAN - 11", Int64.Type}, {"EHCP PAN - 12", type any}, {"EHCP PAN - 13", type any}, {"EHCP PAN - 14", type any}, {"EHCP FPAN - E1", type any}, {"EHCP FPAN - E2", type any}, {"EHCP FPAN - N1", type any}, {"EHCP FPAN - N2", type any}, {"EHCP FPAN - R", Int64.Type}, {"EHCP FPAN - 1", Int64.Type}, {"EHCP FPAN - 2", Int64.Type}, {"EHCP FPAN - 3", Int64.Type}, {"EHCP FPAN - 4", Int64.Type}, {"EHCP FPAN - 5", Int64.Type}, {"EHCP FPAN - 6", Int64.Type}, {"EHCP FPAN - 7", Int64.Type}, {"EHCP FPAN - 8", Int64.Type}, {"EHCP FPAN - 9", Int64.Type}, {"EHCP FPAN - 10", Int64.Type}, {"EHCP FPAN - 11", Int64.Type}, {"EHCP FPAN - 12", type any}, {"EHCP FPAN - 13", type any}, {"EHCP FPAN - 14", type any}, {"Total NOR", Int64.Type}, {"Total PAN", Int64.Type}, {"Total FPAN", Int64.Type}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Changed Type2",{{"School Name", type text}, {"URN", Int64.Type}, {"NOR - E1", Int64.Type}, {"NOR - E2", Int64.Type}, {"NOR - N1", Int64.Type}, {"NOR - N2", Int64.Type}, {"NOR - R", Int64.Type}, {"NOR - 1", Int64.Type}, {"NOR - 2", Int64.Type}, {"NOR - 3", Int64.Type}, {"NOR - 4", Int64.Type}, {"NOR - 5", Int64.Type}, {"NOR - 6", Int64.Type}, {"NOR - 7", Int64.Type}, {"NOR - 8", Int64.Type}, {"NOR - 9", Int64.Type}, {"NOR - 10", Int64.Type}, {"NOR - 11", Int64.Type}, {"NOR - 12", type any}, {"NOR - 13", type any}, {"NOR - 14", type any}, {"PAN - E1", type any}, {"PAN - E2", type any}, {"PAN - N1", Int64.Type}, {"PAN - N2", Int64.Type}, {"PAN - R", Int64.Type}, {"PAN - 1", Int64.Type}, {"PAN - 2", Int64.Type}, {"PAN - 3", Int64.Type}, {"PAN - 4", Int64.Type}, {"PAN - 5", Int64.Type}, {"PAN - 6", Int64.Type}, {"PAN - 7", Int64.Type}, {"PAN - 8", Int64.Type}, {"PAN - 9", Int64.Type}, {"PAN - 10", Int64.Type}, {"PAN - 11", Int64.Type}, {"PAN - 12", type any}, {"PAN - 13", type any}, {"PAN - 14", type any}, {"FPAN - E1", Int64.Type}, {"FPAN - E2", Int64.Type}, {"FPAN - N1", Int64.Type}, {"FPAN - N2", Int64.Type}, {"FPAN - R", Int64.Type}, {"FPAN - 1", Int64.Type}, {"FPAN - 2", Int64.Type}, {"FPAN - 3", Int64.Type}, {"FPAN - 4", Int64.Type}, {"FPAN - 5", Int64.Type}, {"FPAN - 6", Int64.Type}, {"FPAN - 7", Int64.Type}, {"FPAN - 8", Int64.Type}, {"FPAN - 9", Int64.Type}, {"FPAN - 10", Int64.Type}, {"FPAN - 11", Int64.Type}, {"FPAN - 12", type any}, {"FPAN - 13", type any}, {"FPAN - 14", type any}, {"EHCP NOR - E1", type any}, {"EHCP NOR - E2", type any}, {"EHCP NOR - N1", type any}, {"EHCP NOR - N2", type any}, {"EHCP NOR - R", Int64.Type}, {"EHCP NOR - 1", Int64.Type}, {"EHCP NOR - 2", Int64.Type}, {"EHCP NOR - 3", Int64.Type}, {"EHCP NOR - 4", Int64.Type}, {"EHCP NOR - 5", Int64.Type}, {"EHCP NOR - 6", Int64.Type}, {"EHCP NOR - 7", Int64.Type}, {"EHCP NOR - 8", Int64.Type}, {"EHCP NOR - 9", Int64.Type}, {"EHCP NOR - 10", Int64.Type}, {"EHCP NOR - 11", Int64.Type}, {"EHCP NOR - 12", type any}, {"EHCP NOR - 13", type any}, {"EHCP NOR - 14", type any}, {"EHCP PAN - E1", type any}, {"EHCP PAN - E2", type any}, {"EHCP PAN - N1", type any}, {"EHCP PAN - N2", type any}, {"EHCP PAN - R", Int64.Type}, {"EHCP PAN - 1", Int64.Type}, {"EHCP PAN - 2", Int64.Type}, {"EHCP PAN - 3", Int64.Type}, {"EHCP PAN - 4", Int64.Type}, {"EHCP PAN - 5", Int64.Type}, {"EHCP PAN - 6", Int64.Type}, {"EHCP PAN - 7", Int64.Type}, {"EHCP PAN - 8", Int64.Type}, {"EHCP PAN - 9", Int64.Type}, {"EHCP PAN - 10", Int64.Type}, {"EHCP PAN - 11", Int64.Type}, {"EHCP PAN - 12", type any}, {"EHCP PAN - 13", type any}, {"EHCP PAN - 14", type any}, {"EHCP FPAN - E1", type any}, {"EHCP FPAN - E2", type any}, {"EHCP FPAN - N1", type any}, {"EHCP FPAN - N2", type any}, {"EHCP FPAN - R", Int64.Type}, {"EHCP FPAN - 1", Int64.Type}, {"EHCP FPAN - 2", Int64.Type}, {"EHCP FPAN - 3", Int64.Type}, {"EHCP FPAN - 4", Int64.Type}, {"EHCP FPAN - 5", Int64.Type}, {"EHCP FPAN - 6", Int64.Type}, {"EHCP FPAN - 7", Int64.Type}, {"EHCP FPAN - 8", Int64.Type}, {"EHCP FPAN - 9", Int64.Type}, {"EHCP FPAN - 10", Int64.Type}, {"EHCP FPAN - 11", Int64.Type}, {"EHCP FPAN - 12", type any}, {"EHCP FPAN - 13", type any}, {"EHCP FPAN - 14", type any}}),
				    Custom1 = #"Changed Type",
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(Custom1, {"School Name", "URN", "Total NOR", "Total PAN", "Total FPAN", "Source.Name"}, "Attribute", "Value"),
				    #"Removed Duplicates" = Table.Distinct(#"Unpivoted Columns", {"Attribute", "Value"}),
				    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Removed Duplicates", "Text Before Delimiter", each Text.BeforeDelimiter([Attribute], " -"), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Text Before Delimiter",{{"Text Before Delimiter", "Type"}}),
				    #"Inserted Text After Delimiter" = Table.AddColumn(#"Renamed Columns", "Text After Delimiter", each Text.AfterDelimiter([Attribute], "- "), type text),
				    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Text After Delimiter",{{"Text After Delimiter", "Year Group"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Value", Int64.Type}}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Changed Type1",{{"Value", "Number of Pupils"}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Renamed Columns2", "Custom", each if [Year Group] = "E1" then 1 else if [Year Group] = "E2" then 2 else if [Year Group] = "N1" then 3 else if [Year Group] = "N2" then 4 else if [Year Group] = "R" then 5 else if [Year Group] = "1" then 6 else if [Year Group] = "2" then 7 else if [Year Group] = "3" then 8 else if [Year Group] = "4" then 9 else if [Year Group] = "5" then 10 else if [Year Group] = "6" then 11 else if [Year Group] = "7" then 12 else if [Year Group] = "8" then 13 else if [Year Group] = "9" then 14 else if [Year Group] = "10" then 15 else if [Year Group] = "11" then 16 else if [Year Group] = "12" then 17 else if [Year Group] = "13" then 18 else if [Year Group] = "14" then 19 else null, type number),
				    #"Renamed Columns3" = Table.RenameColumns(#"Added Conditional Column",{{"Custom", "Year group Sort Order"}}),
				    #"Added Conditional Column1" = Table.AddColumn(#"Renamed Columns3", "Custom", each if [Type] = "NOR" then 1 else if [Type] = "PAN" then 2 else if [Type] = "FPAN" then 3 else if [Type] = "EHCP NOR" then 4 else if [Type] = "EHCP PAN" then 5 else if [Type] = "EHCP FPAN" then 6 else null, type number)
				in
				    #"Added Conditional Column1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

