table '4 - SEN2 Year Group & Need'
	lineageTag: 2522c981-044a-4120-b1d1-9aa8e09900e4

	column 'Benchmark Comparison Ratios.xlsx'
		dataType: string
		lineageTag: 8d246c50-b653-4f0e-b6bd-cae5e3e696a7
		summarizeBy: none
		sourceColumn: Benchmark Comparison Ratios.xlsx

		annotation SummarizationSetBy = Automatic

	column time_period
		dataType: int64
		formatString: 0
		lineageTag: 23e86054-34a0-4b75-8af9-d4d7f2f2d586
		summarizeBy: sum
		sourceColumn: time_period

		annotation SummarizationSetBy = Automatic

	column region_name
		dataType: string
		lineageTag: 6ad3f501-3beb-4292-9f14-72b8c0a5f127
		summarizeBy: none
		sourceColumn: region_name

		annotation SummarizationSetBy = Automatic

	column old_la_code
		dataType: int64
		formatString: 0
		lineageTag: 268f490b-6447-4c63-b889-d8cb29a0c372
		summarizeBy: sum
		sourceColumn: old_la_code

		annotation SummarizationSetBy = Automatic

	column la_name
		dataType: string
		lineageTag: 50b18cd3-92b1-4dcd-aa0d-2721b3dbcda8
		summarizeBy: none
		sourceColumn: la_name

		annotation SummarizationSetBy = Automatic

	column phase_type_grouping
		dataType: string
		lineageTag: ba820d4f-9df3-487d-823c-ea9c669c009d
		summarizeBy: none
		sourceColumn: phase_type_grouping

		annotation SummarizationSetBy = Automatic

	column pupil_sen_status
		dataType: string
		lineageTag: fa083cbf-545b-473c-829f-3a72310ab598
		summarizeBy: none
		sourceColumn: pupil_sen_status

		annotation SummarizationSetBy = Automatic

	column primary_need
		dataType: string
		lineageTag: e199af42-b26c-490b-803f-a028b1254b11
		summarizeBy: none
		sourceColumn: primary_need

		annotation SummarizationSetBy = Automatic

	column 'Year Group'
		dataType: string
		lineageTag: 8a0775ce-e42b-41de-823d-b36036dd1b40
		summarizeBy: none
		sourceColumn: Year Group

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 7080c169-ffed-4c1d-9450-662010d4d72c
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column 'Benchmark Comparators'
		dataType: string
		lineageTag: c5bf30df-ae86-453c-b647-c675d6d80d14
		summarizeBy: none
		sourceColumn: Benchmark Comparators

		annotation SummarizationSetBy = Automatic

	column 'Nr of Pupils'
		dataType: int64
		formatString: 0
		lineageTag: 1b52b4d1-f51b-4878-9f7c-4e5da39eefc5
		summarizeBy: sum
		sourceColumn: Nr of Pupils

		annotation SummarizationSetBy = Automatic

	partition '4 - SEN2 Year Group & Need' = m
		mode: import
		source =
				let
				    Source = SharePoint.Files("https://1stplanner1.sharepoint.com/sites/1stPlannerInsites", [ApiVersion = 15]),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Name] = "Benchmark Comparison Ratios.xlsx")),
				    #"Filtered Hidden Files1" = Table.SelectRows(#"Filtered Rows", each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (22)", each #"Transform File (22)"([Content])),
				    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File (22)"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (22)", Table.ColumnNames(#"Transform File (22)"(#"Sample File (22)"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"sen_ncyear Data From DfE", type any}, {"Column2", type any}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type any}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type any}, {"", type any}, {"_1", type any}, {"_2", type any}, {"_3", type any}, {"_4", type any}, {"_5", type any}, {"_6", type any}, {"_7", type any}, {" -  -  - ", type text}, {"_8", type any}, {"_9", type any}, {"_10", type text}, {"_11", type any}, {"_12", type any}, {"_13", type text}, {"_14", type any}, {"_15", type any}, {"_16", type text}, {"_17", type any}, {"_18", type any}, {"_19", type text}, {"_20", type any}, {"_21", type any}, {"_22", type text}, {"_23", type any}, {"_24", type any}, {"_25", type text}, {"_26", type any}, {"_27", type any}, {"_28", type text}, {"_29", type any}, {"_30", type any}, {"_31", type text}}),
				    #"Removed Top Rows" = Table.Skip(#"Changed Type",1),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Benchmark Comparison Ratios.xlsx", type text}, {"Original Order", Int64.Type}, {"time_period", Int64.Type}, {"time_identifier", type text}, {"geographic_level", type text}, {"country_code", type text}, {"country_name", type text}, {"region_name", type text}, {"region_code", type text}, {"new_la_code", type text}, {"old_la_code", Int64.Type}, {"la_name", type text}, {"phase_type_grouping", type text}, {"pupil_sen_status", type text}, {"primary_need", type text}, {"Year Group", type text}, {"Pupils", Int64.Type}, {"1 - Statistical Neighbours", Int64.Type}, {"2 - Regional", Int64.Type}, {"3 - Same Level of Deprivation", Int64.Type}, {"4 - Completed Ofsted LA Review With No WSOA", Int64.Type}, {"5 - Had No 2020/21 DSG Deficit", Int64.Type}, {"A - Commissioning Strategy 1 - Statistical Neighbours with No WSOA and No 202021 DSG Deficit", Int64.Type}, {"B - Commissioning Strategy 2 - Regional LAs with No WSOA and No 202021 DSG Deficit", Int64.Type}, {"C - Commissioning Strategy 3 - LAs with the Same Level of Deprivation No WSOA and No 202021 DSG Deficit", Int64.Type}, {"Lookup Value", type text}, {"Comparator 2022 School Aged Population", Int64.Type}, {"Adjustment to Comparator Value", type number}, {"""Text Joined"" LA IDs", type number}, {"Comparator 2022 School Aged Population_1", Int64.Type}, {"Adjustment to Comparator Value_2", type number}, {"""Text Joined"" LA IDs_3", type number}, {"Comparator 2022 School Aged Population_4", Int64.Type}, {"Adjustment to Comparator Value_5", type number}, {"""Text Joined"" LA IDs_6", type number}, {"Comparator 2022 School Aged Population_7", Int64.Type}, {"Adjustment to Comparator Value_8", type number}, {"""Text Joined"" LA IDs_9", type number}, {"Comparator 2022 School Aged Population_10", Int64.Type}, {"Adjustment to Comparator Value_11", type number}, {"""Text Joined"" LA IDs_12", type number}, {"Comparator 2022 School Aged Population_13", Int64.Type}, {"Adjustment to Comparator Value_14", type number}, {"""Text Joined"" LA IDs_15", Int64.Type}, {"Comparator 2022 School Aged Population_16", Int64.Type}, {"Adjustment to Comparator Value_17", type number}, {"""Text Joined"" LA IDs_18", type number}, {"Comparator 2022 School Aged Population_19", Int64.Type}, {"Adjustment to Comparator Value_20", type number}, {"""Text Joined"" LA IDs_21", type number}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"Original Order", "time_identifier", "geographic_level", "country_code", "country_name", "region_code", "new_la_code"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Pupils", "1 - Selected Local Authority"}, {"1 - Statistical Neighbours", "2 - Statistical Neighbour LAs"}, {"2 - Regional", "3 - Regional LAs"}, {"3 - Same Level of Deprivation", "4 - LAs with Same Level of Deprivation"}, {"4 - Completed Ofsted LA Review With No WSOA", "5 - LAs who Completed Ofsted/CQC Review With No WSOA"}, {"5 - Had No 2020/21 DSG Deficit", "6 - LAs who had No 2020/21 DSG Deficit"}, {"A - Commissioning Strategy 1 - Statistical Neighbours with No WSOA and No 202021 DSG Deficit", "A - CS1 – Exemplar Stat Neighbour LAs"}, {"B - Commissioning Strategy 2 - Regional LAs with No WSOA and No 202021 DSG Deficit", "B - CS2 – Exemplar Regional LAs"}, {"C - Commissioning Strategy 3 - LAs with the Same Level of Deprivation No WSOA and No 202021 DSG Deficit", "C - CS3 – Exemplar LAs with Same Deprivation Level"}}),
				    #"Added Index" = Table.AddIndexColumn(#"Renamed Columns", "Index", 1, 1, Int64.Type),
				    #"Removed Columns1" = Table.RemoveColumns(#"Added Index",{"Lookup Value", "Comparator 2022 School Aged Population", "Adjustment to Comparator Value", """Text Joined"" LA IDs", "Comparator 2022 School Aged Population_1", "Adjustment to Comparator Value_2", """Text Joined"" LA IDs_3", "Comparator 2022 School Aged Population_4", "Adjustment to Comparator Value_5", """Text Joined"" LA IDs_6", "Comparator 2022 School Aged Population_7", "Adjustment to Comparator Value_8", """Text Joined"" LA IDs_9", "Comparator 2022 School Aged Population_10", "Adjustment to Comparator Value_11", """Text Joined"" LA IDs_12", "Comparator 2022 School Aged Population_13", "Adjustment to Comparator Value_14", """Text Joined"" LA IDs_15", "Comparator 2022 School Aged Population_16", "Adjustment to Comparator Value_17", """Text Joined"" LA IDs_18", "Comparator 2022 School Aged Population_19", "Adjustment to Comparator Value_20", """Text Joined"" LA IDs_21"}),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Removed Columns1", {"Benchmark Comparison Ratios.xlsx", "time_period", "region_name", "old_la_code", "la_name", "phase_type_grouping", "pupil_sen_status", "primary_need", "Year Group", "Index"}, "Attribute", "Value"),
				    #"Renamed Columns2" = Table.RenameColumns(#"Unpivoted Columns",{{"Attribute", "Benchmark Comparators"}, {"Value", "Nr of Pupils"}})
				in
				    #"Renamed Columns2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

