table Table
	lineageTag: d64feaa0-a40a-434c-81c3-b36cb76aa8cc

	column Column1
		dataType: string
		lineageTag: 6878cdb6-af70-4f53-b1a6-5f5be8344ce7
		summarizeBy: none
		sourceColumn: Column1
		sortByColumn: Column2

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: int64
		formatString: 0
		lineageTag: c9ca6d4e-f556-4e82-aa17-8464fc495879
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition Table = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("VdA7CgJRDEbhrYRbj5Dc3OdaZqaSKQTFQt2/fyYYsDvwdWddEwtdaPsw65WEHrf7kZYkaV9AGST0flI+4QXJLgrJJhqiLgWiJiWkuFRIMakh1aVBqkkLaS4d0kx6SHcZkG4yQobLhAyTGTJPEYZME9SPhN1iw/GnOLF/AQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Column2 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

