table Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table
	lineageTag: 071eb353-4015-4c86-b0b9-a0824f4202dd

	measure Pupil_Numbers_Characteristics_Caseload = ```
			
			VAR FCS1 = SELECTEDVALUE(Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table[Benchmark_Comparison]) = "Forecast - CS1"
			VAR FCS2 = SELECTEDVALUE(Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table[Benchmark_Comparison]) = "Forecast - CS2"
			VAR FCS3 = SELECTEDVALUE(Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table[Benchmark_Comparison]) = "Forecast - CS3"
			VAR ECS1 = SELECTEDVALUE(Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table[Benchmark_Comparison]) = "A - CS1 - Exemplar Stat Neighbour LAs"
			VAR ECS2 = SELECTEDVALUE(Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table[Benchmark_Comparison]) = "B - CS2 - Exemplar Regional LAs"
			VAR ECS3 = SELECTEDVALUE(Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table[Benchmark_Comparison]) = "C - CS3 - Exemplar LAs with Same Deprivation Level"
			        
			VAR TYCS1 = 
			    CALCULATE(
			        SUM(Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table[pupils]),
			        ALL(Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table[Year]),
			        Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table[Benchmark_Comparison] = "A - CS1 - Exemplar Stat Neighbour LAs"
			    )
			
			VAR TYCS2 = 
			    CALCULATE(
			        SUM(Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table[pupils]),
			        ALL(Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table[Year]),
			        Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table[Benchmark_Comparison] = "B - CS2 - Exemplar Regional LAs"
			    )
			
			VAR TYCS3 = 
			    CALCULATE(
			        SUM(Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table[pupils]),
			        ALL(Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table[Year]),
			        Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table[Benchmark_Comparison] = "C - CS3 - Exemplar LAs with Same Deprivation Level"
			    )       
			
			VAR Y203132CS1 = 
			    CALCULATE(
			        SUM(Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table[pupils]),
			        Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table[Year] = 203132,
			        Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table[Benchmark_Comparison] = "Forecast - CS1"
			    )
			
			VAR Y203132CS2 = 
			    CALCULATE(
			        SUM(Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table[pupils]),
			        Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table[Year] = 203132,
			        Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table[Benchmark_Comparison] = "Forecast - CS2"
			    )    
			
			VAR Y203132CS3 = 
			    CALCULATE(
			        SUM(Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table[pupils]),
			        Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table[Year] = 203132,
			        Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table[Benchmark_Comparison] = "Forecast - CS3"
			    )
			    
			VAR ECS1Blank = (TYCS1 = 0)
			VAR ECS2Blank = (TYCS2 = 0)
			VAR ECS3Blank = (TYCS3 = 0)
			
			VAR FCS1Blank = (TYCS1 = 0 && Y203132CS1 = 0)
			VAR FCS2Blank = (TYCS2 = 0 && Y203132CS2 = 0)
			VAR FCS3Blank = (TYCS3 = 0 && Y203132CS3 = 0)
			
			RETURN
			    IF(
			        (ECS1 && ECS1Blank) || (FCS1 && FCS1Blank) ||
			        (ECS2 && ECS2Blank) || (FCS2 && FCS2Blank) ||
			        (ECS3 && ECS3Blank) || (FCS3 && FCS3Blank),
			        BLANK(),
			        SUM(Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table[pupils])
			    )
			```
		formatString: 0
		lineageTag: 7ef62a9d-9a38-4558-909b-1d2befb2c1ab

	column breakdown_topic
		dataType: string
		lineageTag: 33ec1524-b868-4b89-999b-177e1205fa4a
		summarizeBy: none
		sourceColumn: breakdown_topic

		annotation SummarizationSetBy = Automatic

	column breakdown
		dataType: string
		lineageTag: c8ab9d31-fe74-4151-89fc-548def9f5f20
		summarizeBy: none
		sourceColumn: breakdown

		annotation SummarizationSetBy = Automatic

	column old_la_code
		dataType: string
		lineageTag: 28f65126-45b0-481f-95af-7373d5451190
		summarizeBy: none
		sourceColumn: old_la_code

		annotation SummarizationSetBy = Automatic

	column la_name
		dataType: string
		lineageTag: 61e800e3-601c-41e4-afe3-3701eb9bd36a
		summarizeBy: none
		sourceColumn: la_name

		annotation SummarizationSetBy = Automatic

	column Benchmark_Comparison
		dataType: string
		lineageTag: 2482bf6e-98f5-4fb9-bcdf-2a459a049897
		summarizeBy: none
		sourceColumn: Benchmark_Comparison

		annotation SummarizationSetBy = Automatic

	column pupils
		dataType: int64
		formatString: 0
		lineageTag: 7dab9bcf-9f33-419e-903b-f5c04a5307b9
		summarizeBy: sum
		sourceColumn: pupils

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: aa9db4fb-705b-4013-b524-187ab02dbcaf
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	partition Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table = m
		mode: import
		source =
				let
				    Source = Sql.Database("zhy37jcw26quzfiun7rrsrwc7q-mtr6qabpalfeldtgvae7cdnpzu.datawarehouse.fabric.microsoft.com", "Insites_Lakehouse_Gold"),
				    dbo_Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table = Source{[Schema="dbo",Item="Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table"]}[Data]
				in
				    dbo_Full_Comparison_Projection_and_Forcasting_Characteristics_Caseload_Table

