name: Trigger Azure Build (no publish profile)

on:
  push:
    branches:
      - main

jobs:
  notify-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./fabric-api

      - name: "Optional: Run local server for check"
        run: node index.js
        working-directory: ./fabric-api