name: Sync NoR CSV from Azure Blob

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"

jobs:
  sync_csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Ensure output folder exists
        run: mkdir -p public/data

      - name: Download CSV from Azure Blob
        run: |
          echo "📥 Downloading NoR CSV from Azure Blob..."
          curl -L "https://fabricdashdata.blob.core.windows.net/exports/nor_data_combined.csv" -o public/data/nor_data_combined.csv
          echo "✅ Download complete. File size:"
          ls -lh public/data/nor_data_combined.csv

      - name: ✅ Done (no commit — file too large for GitHub)
        run: echo "🎉 Sync complete. File downloaded and ready for local/frontend use."